apiVersion: v1
kind: Service
metadata:
  name: assignment-service
  namespace: assignment
  labels:
    app: assignment
spec:
  type: NodePort
  ports:
  - port: 80
    #protocol: TCP
    targetPort: 80
    nodePort: 30017
